version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repeatedreading-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: repeatedreading
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge 